# Generated by Django 3.2.6 on 2021-08-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubc_uuid', models.CharField(help_text="The user's PUID from ubc.", max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('ubc_id', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('signed_waiver', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('can_play', 'Can Play'), ('suspended', 'Suspended')], max_length=255)),
            ],
        ),
    ]
