# Generated by Django 3.2.6 on 2021-08-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0001_initial'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('team_number', models.IntegerField()),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.pool')),
                ('secondary_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_unit', to='team.unit')),
                ('team_captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to='participant.participant')),
                ('team_roster', models.ManyToManyField(related_name='team_roster', to='participant.Participant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.unit')),
            ],
        ),
    ]
