# Generated by Django 3.2.6 on 2021-09-08 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='location',
            field=models.ForeignKey(help_text="Location where this day's games are to be played.", on_delete=django.db.models.deletion.CASCADE, related_name='days', to='league.location'),
        ),
        migrations.AlterField(
            model_name='day',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='league.week'),
        ),
        migrations.AlterField(
            model_name='pool',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='league.activity'),
        ),
        migrations.AlterField(
            model_name='week',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='league.pool'),
        ),
    ]
