# Generated by Django 3.2.6 on 2021-08-23 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='official',
            name='level',
            field=models.IntegerField(help_text="The official's officiating level.", validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
