# Generated by Django 3.2.6 on 2021-08-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('league', '0001_initial'),
        ('participant', '0001_initial'),
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Date and time when this match is happening.')),
            ],
        ),
        migrations.CreateModel(
            name='TeamGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text="The team's score for the game.")),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('played', 'Played'), ('default', 'Default'), ('forfeit', 'Forfeit')], max_length=255)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text="The player's game jersey number.")),
                ('score', models.PositiveIntegerField(default=0, help_text='The amount of points the player scored.')),
                ('fouls', models.PositiveIntegerField(default=0, help_text='The amount of fouls the player committed.')),
                ('is_mvp', models.BooleanField(default=False, help_text="Is the player the game's MVP?")),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.teamgame')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.participant')),
            ],
        ),
        migrations.CreateModel(
            name='OfficialGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('attended', 'Attended'), ('missed', 'Missed')], max_length=255)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.match')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officials.official')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='match.teamgame'),
        ),
        migrations.AddField(
            model_name='match',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.day'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='match.teamgame'),
        ),
    ]
