# Generated by Django 3.2.6 on 2021-09-08 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_auto_20210908_0046'),
        ('participant', '0001_initial'),
        ('officials', '0002_alter_official_level'),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_away_team', to='match.teamgame'),
        ),
        migrations.AlterField(
            model_name='match',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='league.day'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_home_team', to='match.teamgame'),
        ),
        migrations.AlterField(
            model_name='officialgame',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='match.match'),
        ),
        migrations.AlterField(
            model_name='officialgame',
            name='official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='officials.official'),
        ),
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='match.teamgame'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text="The player's game jersey number.", null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_set', to='participant.participant'),
        ),
    ]
